from typing import Protocol

from app.domain.models import GraphSnapshot


class GraphRepository(Protocol):
    def create_snapshot(self, snapshot: GraphSnapshot) -> None: ...

    def get_snapshot(self, mission_id: str) -> GraphSnapshot: ...

    def save_snapshot(self, snapshot: GraphSnapshot) -> None: ...

    def has_processed_event(self, mission_id: str, event_id: str) -> bool: ...

    def mark_event_processed(self, mission_id: str, event_id: str) -> None: ...

    def has_processed_request(self, mission_id: str, request_id: str) -> bool: ...

    def mark_request_processed(self, mission_id: str, request_id: str) -> None: ...

